### ISSUE TITLE
Component not working anymore

### ISSUE THREAD

**Issue by SeraphimSerapis** [Poeschl/Bring-shoping-list-component#2]
I'm running into the following exception, which seems to be connected to the component's config flow:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 535, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.bring_shopping_list.config_flow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 542, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
```

This error prevents the integration from creating the shopping list sensor.

My config is the following:
```yaml
---
platform: bring_shopping_list
username: !secret bring_user
password: !secret bring_pw
lists:
  - id: !secret bring_list
    name: Home
    locale: de-DE
```

**Comment by Poeschl** [comment]
I wasn't able to find the error in this case. It might be the last issue to make it work. But right now I its not on my todo.

**Comment by XxCabbyoO** [comment]
Same Error fore me. will it still be corrected?

**Comment by XxCabbyoO** [comment]
For Completeness:

Logger: homeassistant.config_entries
Source: config_entries.py:546
First occurred: 22:03:22 (1 occurrences)
Last logged: 22:03:22

Error occurred loading configuration flow for integration bring_shopping_list: No module named 'custom_components.bring_shopping_list.config_flow'

-------

Logger: homeassistant
Source: config_entries.py:551
First occurred: 22:03:22 (1 occurrences)
Last logged: 22:03:22

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 544, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.bring_shopping_list.config_flow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler

-----

**Comment by Poeschl** [comment]
@SeraphimSerapis tried to make it work, I think.
Currently I'm not developing on this integration.

**Comment by SeraphimSerapis** [comment]
I am afraid I didn't find the time to look into this yet. While I'd love to have a working bring component, I've been too busy with other things to spend time in rewriting the integration from scratch.

**Comment by p6002** [comment]
Not working, delete it!
